import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class QuoteService {

  gymQuotes: string[] = [
    "Push yourself, because no one else is going to do it for you.",
    "Success starts with self-discipline.",
    "No pain, no gain. Shut up and train.",
    "Train insane or remain the same.",
    "Your body can stand almost anything. It’s your mind that you have to convince.",
    "What seems impossible today will one day become your warm-up.",
    "Don’t limit your challenges, challenge your limits.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only bad workout is the one that didn’t happen.",
    "Sweat is fat crying.",
    "Excuses don’t burn calories.",
    "Stop wishing. Start doing.",
    "A one hour workout is 4% of your day. No excuses.",
    "It never gets easier, you just get stronger.",
    "Strong is not just physical.",
    "Strive for progress, not perfection.",
    "Discipline is choosing between what you want now and what you want most.",
    "You don’t find will power, you create it.",
    "Success is what comes after you stop making excuses.",
    "Push yourself, because no one else is going to do it for you.",
    "Success starts with self-discipline.",
    "No pain, no gain. Shut up and train.",
    "Train insane or remain the same.",
    "Your body can stand almost anything. It’s your mind that you have to convince.",
    "What seems impossible today will one day become your warm-up.",
    "Don’t limit your challenges, challenge your limits.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only bad workout is the one that didn’t happen.",
    "Sweat is fat crying.",
    "Excuses don’t burn calories.",
    "Stop wishing. Start doing.",
    "A one hour workout is 4% of your day. No excuses.",
    "It never gets easier, you just get stronger.",
    "Strong is not just physical.",
    "Strive for progress, not perfection.",
    "Discipline is choosing between what you want now and what you want most.",
    "You don’t find will power, you create it.",
    "Success is what comes after you stop making excuses.",
    "Push yourself, because no one else is going to do it for you.",
    "Success starts with self-discipline.",
    "No pain, no gain. Shut up and train.",
    "Train insane or remain the same.",
    "Your body can stand almost anything. It’s your mind that you have to convince.",
    "What seems impossible today will one day become your warm-up.",
    "Don’t limit your challenges, challenge your limits.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only bad workout is the one that didn’t happen.",
    "Sweat is fat crying.",
    "Excuses don’t burn calories.",
    "Stop wishing. Start doing.",
    "A one hour workout is 4% of your day. No excuses.",
    "It never gets easier, you just get stronger.",
    "Strong is not just physical.",
    "Strive for progress, not perfection.",
    "Discipline is choosing between what you want now and what you want most.",
    "You don’t find will power, you create it.",
    "Success is what comes after you stop making excuses.",
    "Push yourself, because no one else is going to do it for you.",
    "Success starts with self-discipline.",
    "No pain, no gain. Shut up and train.",
    "Train insane or remain the same.",
    "Your body can stand almost anything. It’s your mind that you have to convince.",
    "What seems impossible today will one day become your warm-up.",
    "Don’t limit your challenges, challenge your limits.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only bad workout is the one that didn’t happen.",
    "Sweat is fat crying.",
    "Excuses don’t burn calories.",
    "Stop wishing. Start doing.",
    "A one hour workout is 4% of your day. No excuses.",
    "It never gets easier, you just get stronger.",
    "Strong is not just physical.",
    "Strive for progress, not perfection.",
    "Discipline is choosing between what you want now and what you want most.",
    "You don’t find will power, you create it.",
    "Success is what comes after you stop making excuses.",
    "Push yourself, because no one else is going to do it for you.",
    "Success starts with self-discipline.",
    "No pain, no gain. Shut up and train.",
    "Train insane or remain the same.",
    "Your body can stand almost anything. It’s your mind that you have to convince.",
    "What seems impossible today will one day become your warm-up.",
    "Don’t limit your challenges, challenge your limits.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only bad workout is the one that didn’t happen.",
    "Sweat is fat crying.",
    "Excuses don’t burn calories.",
    "Stop wishing. Start doing.",
    "A one hour workout is 4% of your day. No excuses.",
    "It never gets easier, you just get stronger.",
    "Strong is not just physical.",
    "Strive for progress, not perfection.",
    "Discipline is choosing between what you want now and what you want most.",
    "You don’t find will power, you create it.",
    "Success is what comes after you stop making excuses.",
    "Push yourself, because no one else is going to do it for you.",
    "Success starts with self-discipline.",
    "No pain, no gain. Shut up and train.",
    "Train insane or remain the same.",
    "Your body can stand almost anything. It’s your mind that you have to convince.",
    "What seems impossible today will one day become your warm-up.",
    "Don’t limit your challenges, challenge your limits.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only bad workout is the one that didn’t happen.",
    "Sweat is fat crying.",
    "Excuses don’t burn calories.",
    "Stop wishing. Start doing.",
    "A one hour workout is 4% of your day. No excuses.",
    "It never gets easier, you just get stronger.",
    "Strong is not just physical.",
    "Strive for progress, not perfection.",
    "Discipline is choosing between what you want now and what you want most.",
    "You don’t find will power, you create it.",
    "Success is what comes after you stop making excuses.",
    "Push yourself, because no one else is going to do it for you.",
    "Success starts with self-discipline.",
    "No pain, no gain. Shut up and train.",
    "Train insane or remain the same.",
    "Your body can stand almost anything. It’s your mind that you have to convince.",
    "What seems impossible today will one day become your warm-up.",
    "Don’t limit your challenges, challenge your limits.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only bad workout is the one that didn’t happen.",
    "Sweat is fat crying.",
    "Excuses don’t burn calories.",
    "Stop wishing. Start doing.",
    "A one hour workout is 4% of your day. No excuses.",
    "It never gets easier, you just get stronger.",
    "Strong is not just physical.",
    "Strive for progress, not perfection.",
    "Discipline is choosing between what you want now and what you want most.",
    "You don’t find will power, you create it.",
    "Success is what comes after you stop making excuses.",
    "Push yourself, because no one else is going to do it for you.",
    "Success starts with self-discipline.",
    "No pain, no gain. Shut up and train.",
    "Train insane or remain the same.",
    "Your body can stand almost anything. It’s your mind that you have to convince.",
    "What seems impossible today will one day become your warm-up.",
    "Don’t limit your challenges, challenge your limits.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only bad workout is the one that didn’t happen.",
    "Sweat is fat crying.",
    "Excuses don’t burn calories.",
    "Stop wishing. Start doing.",
    "A one hour workout is 4% of your day. No excuses.",
    "It never gets easier, you just get stronger.",
    "Strong is not just physical.",
    "Strive for progress, not perfection.",
    "Discipline is choosing between what you want now and what you want most.",
    "You don’t find will power, you create it.",
    "Success is what comes after you stop making excuses.",
    "Push yourself, because no one else is going to do it for you.",
    "Success starts with self-discipline.",
    "No pain, no gain. Shut up and train.",
    "Train insane or remain the same.",
    "Your body can stand almost anything. It’s your mind that you have to convince.",
    "What seems impossible today will one day become your warm-up.",
    "Don’t limit your challenges, challenge your limits.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only bad workout is the one that didn’t happen.",
    "Sweat is fat crying.",
    "Excuses don’t burn calories.",
    "Stop wishing. Start doing.",
    "A one hour workout is 4% of your day. No excuses.",
    "It never gets easier, you just get stronger.",
    "Strong is not just physical.",
    "Strive for progress, not perfection.",
    "Discipline is choosing between what you want now and what you want most.",
    "You don’t find will power, you create it.",
    "Success is what comes after you stop making excuses.",
    "Push yourself, because no one else is going to do it for you.",
    "Success starts with self-discipline.",
    "No pain, no gain. Shut up and train.",
    "Train insane or remain the same.",
    "Your body can stand almost anything. It’s your mind that you have to convince.",
    "What seems impossible today will one day become your warm-up.",
    "Don’t limit your challenges, challenge your limits.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only bad workout is the one that didn’t happen.",
    "Sweat is fat crying.",
    "Excuses don’t burn calories.",
    "Stop wishing. Start doing.",
    "A one hour workout is 4% of your day. No excuses.",
    "It never gets easier, you just get stronger.",
    "Strong is not just physical.",
    "Strive for progress, not perfection.",
    "Discipline is choosing between what you want now and what you want most.",
    "You don’t find will power, you create it.",
    "Success is what comes after you stop making excuses.",
    "Push yourself, because no one else is going to do it for you.",
    "Success starts with self-discipline.",
    "No pain, no gain. Shut up and train.",
    "Train insane or remain the same.",
    "Your body can stand almost anything. It’s your mind that you have to convince.",
    "What seems impossible today will one day become your warm-up.",
    "Don’t limit your challenges, challenge your limits.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only bad workout is the one that didn’t happen.",
    "Sweat is fat crying.",
    "Excuses don’t burn calories.",
    "Stop wishing. Start doing.",
    "A one hour workout is 4% of your day. No excuses.",
    "It never gets easier, you just get stronger.",
    "Strong is not just physical.",
    "Strive for progress, not perfection.",
    "Discipline is choosing between what you want now and what you want most.",
    "You don’t find will power, you create it.",
    "Success is what comes after you stop making excuses.",
    "Push yourself, because no one else is going to do it for you.",
    "Success starts with self-discipline.",
    "No pain, no gain. Shut up and train.",
    "Train insane or remain the same.",
    "Your body can stand almost anything. It’s your mind that you have to convince.",
    "What seems impossible today will one day become your warm-up.",
    "Don’t limit your challenges, challenge your limits.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only bad workout is the one that didn’t happen.",
    "Sweat is fat crying.",
    "Excuses don’t burn calories.",
    "Stop wishing. Start doing.",
    "A one hour workout is 4% of your day. No excuses.",
    "It never gets easier, you just get stronger.",
    "Strong is not just physical.",
    "Strive for progress, not perfection.",
    "Discipline is choosing between what you want now and what you want most.",
    "You don’t find will power, you create it.",
    "Success is what comes after you stop making excuses.",
    "Push yourself, because no one else is going to do it for you.",
    "Success starts with self-discipline.",
    "No pain, no gain. Shut up and train.",
    "Train insane or remain the same.",
    "Your body can stand almost anything. It’s your mind that you have to convince.",
    "What seems impossible today will one day become your warm-up.",
    "Don’t limit your challenges, challenge your limits.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only bad workout is the one that didn’t happen.",
    "Sweat is fat crying.",
    "Excuses don’t burn calories.",
    "Stop wishing. Start doing.",
    "A one hour workout is 4% of your day. No excuses.",
    "It never gets easier, you just get stronger.",
    "Strong is not just physical.",
    "Strive for progress, not perfection.",
    "Discipline is choosing between what you want now and what you want most.",
    "You don’t find will power, you create it.",
    "Success is what comes after you stop making excuses.",
    "Push yourself, because no one else is going to do it for you.",
    "Success starts with self-discipline.",
    "No pain, no gain. Shut up and train.",
    "Train insane or remain the same.",
    "Your body can stand almost anything. It’s your mind that you have to convince.",
    "What seems impossible today will one day become your warm-up.",
    "Don’t limit your challenges, challenge your limits.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only bad workout is the one that didn’t happen.",
    "Sweat is fat crying.",
    "Excuses don’t burn calories.",
    "Stop wishing. Start doing.",
    "A one hour workout is 4% of your day. No excuses.",
    "It never gets easier, you just get stronger.",
    "Strong is not just physical.",
    "Strive for progress, not perfection.",
    "Discipline is choosing between what you want now and what you want most.",
    "You don’t find will power, you create it.",
    "Success is what comes after you stop making excuses.",
    "Push yourself, because no one else is going to do it for you.",
    "Success starts with self-discipline.",
    "No pain, no gain. Shut up and train.",
    "Train insane or remain the same.",
    "Your body can stand almost anything. It’s your mind that you have to convince.",
    "What seems impossible today will one day become your warm-up.",
    "Don’t limit your challenges, challenge your limits.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only bad workout is the one that didn’t happen.",
    "Sweat is fat crying.",
    "Excuses don’t burn calories.",
    "Stop wishing. Start doing.",
    "A one hour workout is 4% of your day. No excuses.",
    "It never gets easier, you just get stronger.",
    "Strong is not just physical.",
    "Strive for progress, not perfection.",
    "Discipline is choosing between what you want now and what you want most.",
    "You don’t find will power, you create it.",
    "Success is what comes after you stop making excuses.",
    "Push yourself, because no one else is going to do it for you.",
    "Success starts with self-discipline.",
    "No pain, no gain. Shut up and train.",
    "Train insane or remain the same.",
    "Your body can stand almost anything. It’s your mind that you have to convince.",
    "What seems impossible today will one day become your warm-up.",
    "Don’t limit your challenges, challenge your limits.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only bad workout is the one that didn’t happen.",
    "Sweat is fat crying.",
    "Excuses don’t burn calories.",
    "Stop wishing. Start doing.",
    "A one hour workout is 4% of your day. No excuses.",
    "It never gets easier, you just get stronger.",
    "Strong is not just physical.",
    "Strive for progress, not perfection.",
    "Discipline is choosing between what you want now and what you want most.",
    "You don’t find will power, you create it.",
    "Success is what comes after you stop making excuses.",
    "Push yourself, because no one else is going to do it for you.",
    "Success starts with self-discipline.",
    "No pain, no gain. Shut up and train.",
    "Train insane or remain the same.",
    "Your body can stand almost anything. It’s your mind that you have to convince.",
    "What seems impossible today will one day become your warm-up.",
    "Don’t limit your challenges, challenge your limits.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only bad workout is the one that didn’t happen.",
    "Sweat is fat crying.",
    "Excuses don’t burn calories.",
    "Stop wishing. Start doing.",
    "A one hour workout is 4% of your day. No excuses.",
    "It never gets easier, you just get stronger.",
    "Strong is not just physical.",
    "Strive for progress, not perfection.",
    "Discipline is choosing between what you want now and what you want most.",
    "You don’t find will power, you create it.",
    "Success is what comes after you stop making excuses.",
    "Push yourself, because no one else is going to do it for you.",
    "Success starts with self-discipline.",
    "No pain, no gain. Shut up and train.",
    "Train insane or remain the same.",
    "Your body can stand almost anything. It’s your mind that you have to convince.",
    "What seems impossible today will one day become your warm-up.",
    "Don’t limit your challenges, challenge your limits.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "The only bad workout is the one that didn’t happen.",
    "Sweat is fat crying.",
    "Excuses don’t burn calories.",
    "Stop wishing. Start doing.",
    "A one hour workout is 4% of your day. No excuses.",
    "It never gets easier, you just get stronger.",
    "Strong is not just physical.",
    "Strive for progress, not perfection.",
    "Discipline is choosing between what you want now and what you want most.",
    "You don’t find will power, you create it.",
    "Success is what comes after you stop making excuses.",
    "Push yourself, because no one else is going to do it for you.",
    "Success starts with self-discipline.",
    "No pain, no gain. Shut up and train.",
    "Train insane or remain the same.",
    "Your body can stand almost anything. It’s your mind that you have to convince."
  ];


  constructor() { }

  getQuoteOfTheDay(): string {
    const today = new Date();
    const start = new Date(today.getFullYear(), 0, 0);
    const diff = today.getTime() - start.getTime();
    const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
    return this.gymQuotes[dayOfYear % this.gymQuotes.length]
  }
}
